# Generated by Django 2.0.5 on 2018-07-03 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='photo',
            new_name='image',
        ),
        migrations.AddField(
            model_name='benefactor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='benefactor', to=settings.AUTH_USER_MODEL),
        ),
    ]
