# Generated by Django 2.0.5 on 2018-07-03 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180703_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('website', models.URLField()),
                ('license', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('budget', models.CharField(choices=[('card', '1'), ('account', '2')], max_length=1)),
                ('city', models.CharField(choices=[('blank', 'blank'), ('تهران', 'Tehran'), ('مشهد', 'Mashhad'), ('اصفهان', 'Isfahan'), ('شیراز', 'Shairaz')], max_length=15)),
                ('description', models.TextField(max_length=300)),
                ('paymethod', models.IntegerField(default=1)),
                ('cardno', models.CharField(blank=True, max_length=20)),
                ('accno', models.CharField(blank=True, max_length=25)),
                ('alreadyPaid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='benefactor',
            old_name='sex',
            new_name='gender',
        ),
    ]
