# Generated by Django 2.0.5 on 2018-07-13 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180703_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('f1', models.IntegerField()),
                ('f2', models.IntegerField()),
                ('f3', models.IntegerField()),
                ('f4', models.IntegerField()),
                ('f5', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('ratedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability', to='users.Ability')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
        migrations.AddField(
            model_name='benefactor',
            name='address',
            field=models.CharField(default='st', max_length=100),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='city',
            field=models.CharField(choices=[('blank', 'blank'), ('تهران', 'Tehran'), ('مشهد', 'Mashhad'), ('اصفهان', 'Isfahan'), ('شیراز', 'Shairaz')], default='blank', max_length=10),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='day',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefactor',
            name='education',
            field=models.CharField(choices=[('nothing', 'nothing'), ('diploma', 'diploma'), ('bachelor', 'bachelor'), ('master', 'master'), ('phd', 'phd')], default='nothing', max_length=10),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='major',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='benefactor',
            name='month',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefactor',
            name='nationalId',
            field=models.CharField(default=123456789, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefactor',
            name='phone',
            field=models.CharField(default=88776655, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='benefactor',
            name='year',
            field=models.IntegerField(default=1347),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='city',
            field=models.CharField(choices=[('blank', 'blank'), ('تهران', 'Tehran'), ('مشهد', 'Mashhad'), ('اصفهان', 'Isfahan'), ('شیراز', 'Shairaz')], default='blank', max_length=10),
        ),
        migrations.AddField(
            model_name='organizer',
            name='day',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='month',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizer',
            name='year',
            field=models.IntegerField(default=1378),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('blank', 'blank')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='alreadyPaid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='paymethod',
            field=models.CharField(choices=[('card', '1'), ('account', '2')], max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userabilities',
            unique_together={('abilityId', 'username')},
        ),
    ]
