# Generated by Django 2.0.5 on 2018-07-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180714_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefactor',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
