# Generated by Django 2.0.5 on 2018-07-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180714_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='alreadyPaid',
            field=models.IntegerField(default=0),
        ),
    ]
