# Generated by Django 2.0.5 on 2018-07-13 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20180714_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabilities',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefactorusername', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
