# Generated by Django 2.0.5 on 2018-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180718_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='C:/Users/asus/Desktop/userTest/media/profile_pics/no-picture.png', upload_to='profile_pics/'),
        ),
    ]
