# Generated by Django 2.0.5 on 2018-07-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180718_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='/profile_pics/no-picture.png', upload_to='profile_pics/'),
        ),
    ]
