# Generated by Django 2.0.5 on 2018-07-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180718_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='a0',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a1',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a10',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a11',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a12',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a13',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a14',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a15',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a16',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a17',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a18',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a19',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a2',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a20',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a21',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a22',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a23',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a24',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a25',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a26',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a27',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a3',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a4',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a5',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a6',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a7',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a8',
            field=models.CharField(default='off', max_length=5),
        ),
        migrations.AddField(
            model_name='weeklyschedule',
            name='a9',
            field=models.CharField(default='off', max_length=5),
        ),
    ]
