# Generated by Django 2.0.5 on 2018-07-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180719_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='wId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userWeek', to='users.WeeklySchedule'),
            preserve_default=False,
        ),
    ]
