# Generated by Django 2.0.5 on 2018-07-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_benefactor_wid'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefactor',
            name='typeOfCooperation',
            field=models.CharField(choices=[('inOffice10', 'inOffice10'), ('inOffice20', 'inOffice20'), ('inOffice30', 'inOffice30'), ('inOfficemore', 'inOfficemore'), ('atHome', 'atHome')], default='inOffice10', max_length=15),
        ),
    ]
