# Generated by Django 2.0.7 on 2018-07-20 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_benefactor_typeofcooperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='users.Category')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='users.Project')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TotalRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalRate', models.FloatField()),
                ('f1', models.FloatField()),
                ('f2', models.FloatField()),
                ('f3', models.FloatField()),
                ('f4', models.FloatField()),
                ('f5', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='benefactor',
            name='education',
            field=models.CharField(choices=[('nothing', 'nothing'), ('diploma', 'دیپلم و فوق دیپلم'), ('bachelor', 'لیسانس'), ('master', 'فوق لیسانس'), ('phd', 'دکترا')], default='nothing', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='categoryproject',
            unique_together={('categoryId', 'projectId')},
        ),
    ]
