# Generated by Django 2.0.7 on 2018-07-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180720_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('wId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week', to='users.WeeklySchedule')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ability1', to='users.Ability')),
                ('reqId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement1', to='users.Requirement')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='requirementabilities',
            unique_together={('abilityId', 'reqId')},
        ),
    ]
