# Generated by Django 2.0.7 on 2018-07-20 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180720_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementabilities',
            name='abilityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab', to='users.Ability'),
        ),
        migrations.AlterField(
            model_name='requirementabilities',
            name='reqId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='req', to='users.Requirement'),
        ),
    ]
