# Generated by Django 2.0.7 on 2018-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180720_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
