# Generated by Django 2.0.5 on 2018-07-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_totalrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='../media/profile_pics/no-picture.png', upload_to='profile_pics/'),
        ),
    ]
