# Generated by Django 2.0.5 on 2018-07-20 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20180720_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='gender',
        ),
        migrations.AddField(
            model_name='requirement',
            name='description',
            field=models.TextField(default='blank', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='typeOfCooperation',
            field=models.CharField(choices=[('inOffice10', 'inOffice10'), ('inOffice20', 'inOffice20'), ('inOffice30', 'inOffice30'), ('inOfficemore', 'inOfficemore'), ('atHome', 'atHome')], default='inOffice10', max_length=15),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
