# Generated by Django 2.0.5 on 2018-07-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20180721_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
